version: "3.9"

services:
    redis:
        image: redis:latest
        container_name: redis
        ports: [ "6379:6379" ]
        volumes:
            - redis:/data
        networks: [ network ]
    app:
        image: stadio_chalange
        container_name: stadio_chalange
        build:
            context: .
            dockerfile: Dockerfile
        ports: [ "8181:8181" ]
        networks: [ network ]
networks:
    network:
        name: network
        driver: bridge

volumes:
    redis:
        name: redis
        driver: local
